routes/api.py
import json
from flask import Blueprint, Response, request, render_template, url_for
from requests.exceptions import ConnectionError
import api_functions
import class_agents
import class_pingbacks
import class_reportingsystems
import class_reports
import routes.api_functions
from database import queries
from modules.ldapi import LDAPI

api = Blueprint('api', __name__)


@api.route('/function/lodge-agent', methods=['POST'])
def lodge_agent():
    """Insert an Agent into the provenance database"""
    # only accept RDF documents
    acceptable_mimes = LDAPI.get_rdf_mimetypes_list()
    ct = request.content_type
    if ct not in acceptable_mimes:
        return api_functions.client_error_response(
            'The Agent posted is not encoded with a valid RDF Content-Type. Must be one of: ' +
            ', '.join(acceptable_mimes) + '.')

    # validate Agent
    sr = class_agents.IncomingAgent(request.data, request.content_type)
    if not sr.valid():
        return api_functions.client_error_response(
            'The Agent posted is not valid for the following reasons: ' +
            ', '.join(sr.error_messages) + '.')

    # get the Agent's URI
    sr.determine_uri()

    # store the Agent
    if not sr.stored():
        return api_functions.server_error_response(
            'The Agent posted is valid but cannot be stored for the following reasons: ' +
            ', '.join(sr.error_messages) + '.')

    # reply to sender
    return Response(
        sr.uri,
        status=201,
        mimetype='text/plain')


@api.route('/function/create-agent')
def create_agent():
    """Create an Agent for inserting into the provenance database using an HTML web form"""
    try:
        agents = routes.api_functions.get_agents()
    except ConnectionError:
        return render_template('error_db_connection.html'), 500
    return render_template(
        'function_create_agent.html',
        agents=agents
    )


@api.route('/function/lodge-reportingsystem', methods=['POST'])
def lodge_reportingsystem():
    """Insert a ReportingSystem into the provenance database"""
    # only accept RDF documents
    acceptable_mimes = LDAPI.get_rdf_mimetypes_list()
    ct = request.content_type
    if ct not in acceptable_mimes:
        return api_functions.client_error_response(
            'The ReportingSystem posted is not encoded with a valid RDF Content-Type. Must be one of: ' +
            ', '.join(acceptable_mimes) + '.')

    # validate ReportingSystem
    rs = class_reportingsystems.IncomingReportingSystem(request)
    if not rs.valid():
        return api_functions.client_error_response(
            'The ReportingSystem posted is not valid for the following reasons: ' +
            ', '.join(rs.error_messages) + '.')

    # get the ReportingSystem's URI
    rs.determine_uri()

    rs.generate_named_graph_metadata()

    # store the ReportingSystem
    if not rs.stored():
        return api_functions.server_error_response(
            'ReportingSystem posted is valid but cannot be stored for the following reasons: ' +
            ', '.join(rs.error_messages) + '.')

    # reply to sender
    return Response(
        rs.uri,
        status=201,
        mimetype='text/plain')


@api.route('/function/create-reportingsystem')
def create_reportingsystem():
    """Create a ReportingSystem for inserting into the provenance database using an HTML web form"""
    try:
        agents = routes.api_functions.get_agents()
    except ConnectionError:
        return render_template('error_db_connection.html'), 500
    return render_template(
        'function_create_reportingsystem.html',
        agents=agents
    )


@api.route('/function/lodge-report', methods=['POST'])
def lodge_report():
    """Insert a Report into the provenance database"""
    # only accept RDF documents
    acceptable_mimes = LDAPI.get_rdf_mimetypes_list()
    ct = request.content_type
    if ct not in acceptable_mimes:
        return api_functions.client_error_response(
            'The Report posted is not encoded with a valid RDF Content-Type. Must be one of: ' +
            ', '.join(acceptable_mimes) + '.')

    # validate Report
    r = class_reports.IncomingReport(request)
    if not r.valid():
        return api_functions.client_error_response(
            'The Report posted is not valid for the following reasons: ' + ', '.join(r.error_messages) + '.')

    # get the Report's URI
    r.determine_uri()

    r.generate_named_graph_metadata()

    # store the Report
    if not r.stored():
        return api_functions.server_error_response(
            'Report posted is valid but cannot be stored for the following reasons: ' +
            ', '.join(r.error_messages) + '.')

    # kick off any Pingbacks for this Report, as per chosen Pingbacks strategies
    # TODO: split this off into another thread
    from modules.pingbacks.engine import Engine
    e = Engine(r.graph, r.uri, url_for('modelx.instance'), url_for('.sparql'))

    # reply to sender
    return r.uri, 201


@api.route('/function/create-report')
def create_report():
    """Create a Report for inserting into the provenance database using an HTML web form"""
    try:
        reportingsystems = routes.api_functions.get_reportingsystems()
        agents = routes.api_functions.get_agents()
        entities = routes.api_functions.get_entities()
    except ConnectionError:
        return render_template('error_db_connection.html'), 500

    return render_template(
        'function_create_report.html',
        agents=agents,
        entities=entities,
        reportingsystems=reportingsystems
    )


@api.route('/function/lodge-pingback', methods=['POST'])
def lodge_pingback():
    """Insert an Pingback into the provenance database' pingbacks data named graph"""
    # only valid Pingback Cotent-Types
    acceptable_mimes = class_pingbacks.IncomingPingback.acceptable_mimes
    ct = request.content_type
    if ct not in acceptable_mimes:
        return api_functions.client_error_response(
            'The Pingback posted is not encoded with a valid Content-Type. Must be one of: ' +
            ', '.join(acceptable_mimes) + '.')

    # validate Pingback
    p = class_pingbacks.IncomingPingback(request)
    if not p.valid():
        return api_functions.client_error_response(
            'The Pingback posted is not valid for the following reasons: ' + ', '
            .join(p.error_messages) + '.')

    # get the Pingback's URI
    p.determine_uri()

    # convert the Pingback to RDF -- no need to test this step as successful validation, needed to get this far, ensures
    # it can be converted
    # this function also generated Named Graph metadata
    p.convert_pingback_to_rdf()

    p.generate_named_graph_metadata()

    # store the Pingback's RDF
    if not p.stored():
        return api_functions.server_error_response(
            'Report posted is valid but cannot be stored for the following reasons: , '
            .join(p.error_messages) + '.')

    # reply to sender
    return '', 204  # PROV-AQ says to return an empty 204 response


@api.route('/function/sparql', methods=['GET', 'POST'])
def sparql():
    # Query submitted
    if request.method == 'POST':
        '''
        Pass on the SPARQL query to the underlying system PROMS is using (Fuseki etc.)
        '''
        query = None
        if request.content_type == 'application/x-www-form-urlencoded':
            '''
            https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-via-post-urlencoded

            2.1.2 query via POST with URL-encoded parameters

            Protocol clients may send protocol requests via the HTTP POST method by URL encoding the parameters. When
            using this method, clients must URL percent encode all parameters and include them as parameters within the
            request body via the application/x-www-form-urlencoded media type with the name given above. Parameters must
            be separated with the ampersand (&) character. Clients may include the parameters in any order. The content
            type header of the HTTP request must be set to application/x-www-form-urlencoded.
            '''
            if request.form.get('query') is None:
                return api_functions.client_error_response(
                    'Your POST request to PROMS\' SPARQL endpoint must contain a \'query\' parameter if form '
                    'posting is used.')
            else:
                query = request.form.get('query')
        elif request.content_type == 'application/sparql-query':
            '''
            https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-via-post-direct

            2.1.3 query via POST directly

            Protocol clients may send protocol requests via the HTTP POST method by including the query directly and
            unencoded as the HTTP request message body. When using this approach, clients must include the SPARQL query
            string, unencoded, and nothing else as the message body of the request. Clients must set the content type
            header of the HTTP request to application/sparql-query. Clients may include the optional default-graph-uri
            and named-graph-uri parameters as HTTP query string parameters in the request URI. Note that UTF-8 is the
            only valid charset here.
            '''
            query = request.data  # get the raw request
            if query is None:
                return api_functions.client_error_response(
                    'Your POST request to PROMS\' SPARQL endpoint must contain the query in plain text in the '
                    'POST body if the Content-Type \'application/sparql-query\' is used.')

        # sorry, we only return JSON results. See the service description!
        try:
            query_result = queries.query(query)
        except ValueError, e:
            return render_template(
                'function_sparql.html',
                query=query,

routes/class_agents.py
from class_incoming import IncomingClass
import cStringIO
import uuid
from rdflib import Graph
import api_functions
import settings
from modules.ldapi import LDAPI


class IncomingAgent(IncomingClass):
    def __init__(self, data, mimetype):
        IncomingClass.__init__(self, data, mimetype)

    def valid(self):
        """Validates an incoming Agent using direct tests (can it be parsed?) and appropriate RuleSets"""
        # try to parse the Agent data
        try:
            self.graph = Graph().parse(
                cStringIO.StringIO(self.data),
                format=[item[1] for item in LDAPI.MIMETYPES_PARSERS if item[0] == self.mimetype][0]
            )
        except Exception, e:
            self.error_messages = ['The serialised data cannot be parsed. Is it valid RDF?',
                                   'Parser says: ' + e.message]
            return False

        # simple validation here, no RuleSet for now
        # only check if we have a label, >= 3 characters
        q = '''
        PREFIX prov: <http://www.w3.org/ns/prov#>
        ASK
        WHERE {
            ?ag a prov:Agent ;
                rdfs:label ?label .
            FILTER regex(?label, ".{3,}")
        }
        '''
        qres = bool(self.graph.query(q))
        if not qres:
            self.error_messages = ['Agent does not contain an rdfs:label or the label is less than 3 characters long']
            return False

        # if the Report has been parsed, we have found the Report type and it's passed it's relevant RuleSet, it's valid
        return True

    def determine_uri(self):
        """Determines the URI for this Agent"""
        # If this Agent has a placeholder URI, find it and replace it with one generated by PROMS Server
        q = '''
            PREFIX prov: <http://www.w3.org/ns/prov#>
            SELECT ?uri
            WHERE {
                ?uri a prov:Agent .
                FILTER regex(str(?uri), "placeholder")
            }
        '''
        uri = None
        for r in self.graph.query(q):
            uri = r['uri']

        if uri is not None:
            self._generate_new_uri(uri)
        else:
            # since it has an existing URI, not a placeholder one, use the existing one
            q = '''
                PREFIX prov: <http://www.w3.org/ns/prov#>
                SELECT ?uri
                WHERE {
                    ?uri a prov:Agent .
                }
            '''
            for r in self.graph.query(q):
                self.uri = r['uri']

        return True

    def _generate_new_uri(self, old_uri):
        # ask PROMS Server for a new RS URI
        new_uri = settings.AGENT_BASE_URI + str(uuid.uuid4())
        self.uri = new_uri
        # add that new URI to the in-memory graph
        api_functions.replace_uri(self.graph, old_uri, new_uri)

routes/pages.py
"""
HTTP routes for basic HTML pages
"""
import os
from flask import Blueprint, render_template, send_from_directory, request, Response
import settings
from requests.exceptions import ConnectionError
import pages_functions
pages = Blueprint('pages', __name__)


@pages.route('/')
def home():
    if request.args.get('_view') or request.args.get('request') or request.args.get('REQUEST'):
        return Response(
            pages_functions.get_capabilities(),
            status=200,
            mimetype='application/xml'
        )

    return render_template(
        'page_index.html'
    )


@pages.route('/about')
def about():
    return render_template(
        'page_about.html',
        version=settings.VERSION
    )


@pages.route('/contents')
def contents():
    try:
        content_classes = pages_functions.get_contents_classes()
    except ConnectionError:
        return render_template('error_db_connection.html'), 500
    return render_template(
        'page_contents.html',
        content_classes=content_classes
    )


@pages.route('/api')
def api():
    return render_template(
        'page_api.html'
    )


@pages.route('/favicon.ico')
def favicon():
    return send_from_directory(
        os.path.join(settings.HOME_DIR, 'static'),
        'favicon.ico', mimetype='image/vnd.microsoft.icon'
    )


@pages.app_errorhandler(404)
def page_not_found(e):
    return render_template(
        'error_404.html'
    ), 404


@pages.app_errorhandler(405)
def page_not_found(e):
    return render_template(
        'error_405.html'
    ), 405

templates/alternates_view.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    <h2>Alternates view of a <a href="{{ class_uri }}">{{ class_uri }}</a></h2>
    {% if instance_uri %}
        <h3>Instance <a href="{{ instance_uri_encoded }}">{{ instance_uri }}</a></h3>
    {% endif %}
    <table class="lined">
    <tr><th>View</th><th>Formats</th></tr>
    {% for v, fs in views_formats.iteritems() %}
        {% if v == 'default' %}
            <td>default</td><td><a href="{{ request.base_url }}?_uri={{ instance_uri_encoded if instance_uri != None else class_uri_encoded }}&_view={{ fs }}">{{ fs }}</a></td>
        {% else %}
            <tr>
                <td><a href="{{ request.base_url }}?_uri={{ instance_uri_encoded if instance_uri != None else class_uri_encoded }}&_view={{ v }}">{{ v }}</a></td>
                <td>
                {% for f in fs %}
                <a href="{{ request.base_url }}?_uri={{ instance_uri_encoded if instance_uri != None else class_uri_encoded }}&_view={{ v }}&_format={{ f }}">{{ f }}</a>
                {% endfor %}
                </td>
            </tr>
        {% endif %}
    {% endfor %}
    </table>


{% endblock %}

templates/class_activity_prov.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    {% if activity %}
        <h2>An Activity</h2>
        <p><a href="{{ request.url }}">html</a> | <a href="{{ request.url + "&_format=text/turtle" }}">rdf/turtle</a></p>
        <table class="lined">
            <tr><th>URI:</th><td><a href="{{ activity['uri'] }}">{{ activity['uri'] }}</a></td></tr>
            <tr><th>Label:</th><td>{{ activity['label'] }}</td></tr>
            <tr><th>Started:</th><td>{{ activity['sat'] }}</td></tr>
            <tr><th>Ended:</th><td>{{ activity['eat'] }}</td></tr>
            {% if activity['waw_encoded'] is not none  %}
                <tr><th>Was Associated With:</th><td><a href="{{ url_for('modelx.instance') + '?_uri=' + activity['waw_encoded'] }}">activity['waw_label']</a></td></tr>
            {% endif %}
        </table>

        <h3>Alternate views</h3>
        <p>Different view of this object are listed at its <a href="{{ request.url }}&_view=alternates">Alternate views</a> page.</p>

        <h3>PROV view</h3>
        <p>This view of this Entity shows everything from the provenance database known about this Entity, but only things according to the PROV ontology or upper contologies (RDF, RDFS, OWL). Additional facts recorded using other ontologies are not show.</p>
        <textarea style="width:99%; height:200px;">{{ prov_data }}</textarea>

    {% else %}
        <p>No Activity information found.</p>
    {% endif %}
{% endblock %}

templates/class_agent_prov.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    {% if agent %}
        <h2>An Agent</h2>
        <p><a href="{{ request.url }}">html</a> | <a href="{{ request.url + "&_format=text/turtle" }}">rdf/turtle</a></p>
        <table class="lined">
            <tr><th>URI:</th><td><a href="{{ agent['uri'] }}">{{ agent['uri'] }}</a></td></tr>
            <tr><th>Label:</th><td>{{ agent['label'] }}</td></tr>
            {% if agent['aobo'] is not none %}
                <tr><th>Acted Ob Behalf Of:</th><td><a href="{{ activity['aobo'] }}">{{ activity['aobo_label'] }}</a></td></tr>
            {% endif %}
        </table>

        <h3>Alternate views</h3>
        <p>Different view of this object are listed at its <a href="{{ request.url }}&_view=alternates">Alternate views</a> page.</p>

        <h3>PROV view</h3>
        <p>This view of this Entity shows everything from the provenance database known about this Entity, but only things according to the PROV ontology or upper contologies (RDF, RDFS, OWL). Additional facts recorded using other ontologies are not show.</p>
        <textarea style="width:99%; height:200px;">{{ prov_data }}</textarea>

    {% else %}
        <p>No Agent information found.</p>
    {% endif %}
{% endblock %}

templates/class_entity.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    {% if entity %}
        <h2>An Entity</h2>
        <p><a href="{{ request.url }}">html</a> | <a href="{{ request.url }}&_format=text/turtle">rdf/turtle</a></p>
        <table class="lined">
            <tr><th>URI:</th><td><a href="{{ entity['uri'] }}">{{ entity['uri'] }}</a></td></tr>
            {% if entity['label'] is not none %}
                <tr><th>Label:</th><td>{{ entity['label'] }}</td></tr>
            {% endif %}
            {% if entity['value'] is not none %}
                <tr><th>Value:</th><td>{{ entity['value'] }}</td></tr>
            {% endif %}
        </table>

        <h3>Alternate views</h3>
        <p>Different view of this object are listed at its <a href="{{ request.base_url }}?_uri={{ entity['uri_encoded'] }}&_view=alternates">Alternate views</a> page.</p>

        {% if entity['script'] %}
            <h3>Neighbours view</h3>
            <div id="neighbour_view"></div>
            <script type="text/javascript" src="{{ url_for('static', filename='js/raphael-min.js') }}" charset="utf-8"></script>
            <script type="text/javascript" src="{{ url_for('static', filename='js/proms-svg.js') }}" charset="utf-8"></script>
            <script type="text/javascript">
                {{ entity['script'] | safe }}
            </script>
        {% endif %}
    {% else %}
        <p>No Entity information found.</p>
    {% endif %}
{% endblock %}

templates/class_report_prov.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    {% if report %}
        <h2>A {{ report['rt_label'] }} Report</h2>
        <p><a href="{{ request.url }}">html</a> | <a href="{{ request.url }}&_format=text/turtle">rdf/turtle</a></p>
        <table class="lined">
            <tr><th>URI:</th><td><a href="{{ report['uri'] }}">{{ report['uri'] }}</a></td></tr>
            <tr><th>Label:</th><td>{{ report['label'] }}</td></tr>
            <tr><th>Native ID:</th><td>{{ report['nid'] }}</td></tr>
            <tr><th>Generated At Time:</th><td>{{ report['gat'] }}</td></tr>
            <tr><th>Was Reported By:</th><td><a href={{ url_for('modelx.instance') }}?_uri={{ report['rs_encoded'] }}>{{ report['rs_label'] }}</a></td></tr>
        </table>

        <h3>Alternate views</h3>
        <p>Different view of this object are listed at its <a href="{{ request.url }}&_view=alternates">Alternate views</a> page.</p>

        <h3>PROV view</h3>
        <p>This view of this Entity shows everything from the provenance database known about this Entity, but only things according to the PROV ontology or upper contologies (RDF, RDFS, OWL). Additional facts recorded using other ontologies are not show.</p>
        <textarea style="width:99%; height:200px;">{{ prov_data }}</textarea>

    {% else %}
        <p>No Report information found.</p>
    {% endif %}
{% endblock %}

templates/class_reportingsystem.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    <h2>A ReportingSystem</h2>
    <p><a href="{{ request.url }}">html</a> | <a href="{{ request.url + "&_format=text/turtle" }}">rdf/turtle</a></p>
    <table class="lined">
        <tr><th>URI:</th><td><a href="{{ reportingsystem['uri'] }}">{{ reportingsystem['uri'] }}</a></td></tr>
        <tr><th>Label:</th><td>{{reportingsystem['label']}}</td></tr>
        {% if reportingsystem['aobo'] is not none %}
            <tr><th>Acted On Behalf Of:</th><td><a href="{{ reportingsystem['aobo'] }}">{{ reportingsystem['aobo_label'] }}</a></td></tr>
        {% endif %}
    </table>

    <h3>Alternate views</h3>
    <p>Different view of this object are listed at its <a href="{{ request.url }}&_view=alternates">Alternate views</a> page.</p>

    {% if reportingsystem['script'] %}
    <h4>Neighbours view</h4>
        <div id="neighbour_view"></div>
        <script type="text/javascript" src="{{ url_for('static', filename='js/raphael-min.js') }}" charset="utf-8"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/proms-svg.js') }}" charset="utf-8"></script>
        <script type="text/javascript">
            {{ reportingsystem['script'] | safe}}
        </script>
    {% else %}
        <p>No ReportingSystem information found.</p>
    {% endif %}
{% endblock %}

templates/function_sparql.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    <h1>PROMS Server</h1>
    <h2>SPARQL endpoint</h2>
    <h4>Enter your SPARQL query in the text box below:</h4>
     <form action="{{ url_for('api.sparql') }}" method="post">
        <textarea name="query" id="query" style="width:500px; height:300px;">{% if query and query != '' %}{{query}}{% endif %}</textarea>
        <br />
        <input type="hidden" name="form" value="true" />
        <input type="submit" value="Query PROMS" /><br />
        <!--<button id="query-proms">Query PROMS</button><br />-->
        <h4>Result</h4>
        <textarea id="query-result" style="width:500px; height:300px;" readonly>
                {% if query_result != '' %}{{query_result}}{% endif %}
        </textarea>
    </form>
    <script>

    window.onload = function() {
        prettyPrintJSON();
    };
        function prettyPrintJSON() {
            var ugly = document.getElementById('query-result').value;
            var obj = JSON.parse(ugly);
            var pretty = JSON.stringify(obj, undefined, 4);
            document.getElementById('query-result').value = pretty;
        }
    </script>
{% endblock %}

templates/page_api.html
{% extends "template_layout_vanilla.html" %}

{% block content %}
    <h2>The PROMS Server API</h2>
    <h3>Endpoints</h3>
    <table class="lined">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Access</th>
        </tr>
        <tr>
            <th>Instance viewer</th>
            <td>Accesses a single object from the provenance database</td>
            <td>
                <p><a href="{{ url_for('modelx.instance') }}?_uri=">{{ url_for('modelx.instance') }}?_uri={uri}</a></p>
                uri <em>(mandatory)</em>: the URI of an object in the provenance database, URL encoded
            </td>
        </tr>
        <tr>
            <th>Register viewer</th>
            <td>Accesses a register of a single class of object from the provenance database</td>
            <td>
                <p><a href="{{ url_for('modelx.register') }}?_uri=">{{ url_for('modelx.register') }}?_uri={uri}</a></p>
                uri <em>(mandatory)</em>: the URI of a class of object in the provenance database, URL encoded
            </td>
        </tr>
        <tr>
            <th>Register viewer, class name</th>
            <td>Accesses a register of a single one class of object from the provenance database using the class name, not the full URI of the class</td>
            <td>
                <p><a href="{{ url_for('modelx.register') }}">{{ url_for('modelx.register') }}/{class_name}/</a></p>
                class_names available are:
                <ul>
                    <li>Activity</li>
                    <li>Agent</li>
                    <li>Entity</li>
                    <li>Person</li>
                    <li>Report</li>
                    <li>ReportingSystem</li>
                </ul>
            </td>
        </tr>
        <tr>
            <th>SPARQL endpoint</th>
            <td>Provides a read-only <a href="https://www.w3.org/TR/sparql11-overview/">SPARQL 1.1</a> endpoint for the provenance database</td>
            <td>
                <p><a href="{{ url_for('api.sparql') }}">{{ url_for('api.sparql') }}</a></p>
                See the SPARQL endpoint itself for documentation of use
            </td>
        </tr>
        <tr>
            <th>Lodge a <em>ReportingSystem</em></th>
            <td>Manually register a ReportingSystem for which Reports can then be sent to this PROMS Server instance</td>
            <td>
                <p><a href="{{ url_for('api.lodge_reportingsystem') }}">{{ url_for('api.lodge_reportingsystem') }}</a></p>
            </td>
        </tr>
        <tr>
            <th>Create a <em>ReportingSystem</em></th>
            <td>Manually create a PROMS ReportingSystem using a web form</td>
            <td>
                <p><a href="{{ url_for('api.create_reportingsystem') }}">{{ url_for('api.create_reportingsystem') }}</a></p>
            </td>
        </tr>
        <tr>
            <th>Lodge <em>Report</em></th>
            <td>POST a Report to this PROMS Server instance</td>
            <td>
                <p><a href="{{ url_for('api.lodge_report') }}">{{ url_for('api.lodge_report') }}</a></p>
                Must be an <a href="https://en.wikipedia.org/wiki/POST_(HTTP)">HTTP POST</a> request containing a <a href="https://confluence.csiro.au/display/PROMS/Getting+information+into+PROMS+Server">valid PROMS Report</a> for a <a href="https://confluence.csiro.au/display/PROMS/Getting+information+into+PROMS+Server">registered ReportingSystem</a> in one of the following RDF mimetypes: 'text/turtle', 'application/rdf+xml', 'application/rdf+json', 'application/json', 'text/ntriples', 'text/nt', 'text/n3'
            </td>
        </tr>
        <tr>
            <th>Create a <em>Report</em></th>
            <td>Manually create a PROMS Report to download or send to this PROMS Server instance using a web form</td>
            <td>
                <p><a href="{{ url_for('api.create_report') }}">{{ url_for('api.create_report') }}</a></p>
            </td>
        </tr>
        <tr>
            <th>Lodge <em>Pingback</em></th>
            <td>POST a PROV-AQ or a PROMS Pingback to this PROMS Server instance</td>
            <td>
                <p><a href="{{ url_for('api.lodge_pingback') }}">{{ url_for('api.lodge_pingback') }}</a></p>
                <h4>PROV-AQ messages</h4>
                <p>Must use:</p>
                    <ul>
                        <li><a href="{{ url_for('api.lodge_pingback') }}?resource_uri={RESOURCE_URI">{{ url_for('api.lodge_pingback') }}?resource_uri={RESOURCE_URI}</a></li>
                    </ul>
                <p>
                    Where {RESOURCE_URI} is the URI of the resource the pingback is sent for. Given that <a href="https://www.w3.org/TR/prov-aq/">PROV-AQ</a> specifies that a PROV-AQ poingback should be sent to the resource's URI, a redirect from <code>{RESOURCE_URI} --> {{ url_for('api.lodge_pingback') }}?resource_uri={RESOURCE_URI}</code> seems appropriate to implement in front of PROMS Server.
                </p>
                <h4>PROMS messages</h4>
                <p>Must use:</p>
                    <ul>
                        <li><a href="{{ url_for('api.lodge_pingback') }}">{{ url_for('api.lodge_pingback') }}</a></li>
                    </ul>
                <p>PROMS Pingback messages contain the resource information in their body therefore no query string arguments should be supplied.</p>
            </td>
        </tr>

        <!--
        <tr>
            <th>New <em>Pingback</em></th>
            <td>POST a PROV-O or PROMS Pingback to this PROMS Server instance</td>
            <td>
                <p><a href="{{ url_for('api.lodge_pingback') }}">{{ url_for('api.lodge_pingback') }}</a></p>
                Must be an <a href="https://en.wikipedia.org/wiki/POST_(HTTP)">HTTP POST</a> request containing a <a href="http://promsns.org/pingbacks/validator">valid poingback message</a>.
            </td>
        </tr>
        -->
    </table>
{% endblock %}

templates/template_nav_vanilla.html
<div id="vanilla-nav">
	<a href="{{ url_for('pages.home') }}">PROMS Home</a>
	<a href="{{ url_for('pages.api') }}">API</a>
    <a href="{{ url_for('pages.contents') }}">Instance Contents</a>
	<a href="{{ url_for('pages.about') }}">About PROMS</a>
</div>